// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vegypptlhsadrekwagqi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZlZ3lwcHRsaHNhZHJla3dhZ3FpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxOTM1NzIsImV4cCI6MjA2NTc2OTU3Mn0.QA24u4BTHpYCezaiDQAyDFL3BIVABdaEt5Le5jD-RVE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);